### Variáveis globais
@baseUrl = http://localhost:3000
@prod = https://api.seusite.com
@auth = Bearer abc123xyz

### Raiz do servidor
GET {{baseUrl}}/ HTTP/1.1
Content-Type: application/json

### Find all all
GET {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

### Buscar usuário por ID
GET {{baseUrl}}/users/42 HTTP/1.1
Content-Type: application/json

### Enviar formulário (POST)
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "username": "joaosilva",
  "email": "joao@example.com",
  "age": 30
}

### Exemplo com cabeçalhos personalizados
GET {{baseUrl}}/users/123 HTTP/1.1
Authorization: Bearer abc123
X-Custom-Header: meu-valor

### Exemplo com parâmetros de query
GET {{baseUrl}}/users/99?details=true&admin=false HTTP/1.1

### Discord
POST {{baseUrl}}/discord/interactions
Content-Type: application/json

{
  "type": 2,
  "data" : {
    "name": "elysia"
  }
}